### ISSUE TITLE
Should delete temp folders if build fails

### ISSUE THREAD

**Issue by pauljohnleonard** [fintechneo/ngmakelib#1]
Error: EEXIST: file already exists, mkdir '.ngmakelibtmp'

**Comment by petersalomonsen** [comment]
Maybe it's better to not delete on failure, but rather delete if exists before the mkdir command?

**Comment by petersalomonsen** [comment]
@pauljohnleonard  Will now delete working folder (.ngmakelibtmp) from previous failed attempt on startup.
